name: final
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - bottleneck=1.4.2=py311h57dcf0c_0
  - brotlicffi=1.0.9.2=py311h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - cairo=1.18.4=he9e932c_0
  - captum=0.7.0=0
  - catboost=1.2.5=py311h1ea47a8_0
  - certifi=2025.10.5=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py311h214f63a_0
  - cpython=3.11.14=py311hd8ed1ab_2
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - filelock=3.17.0=py311haa95532_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=hd211d86_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py311h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.16=hfd05255_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - getopt-win32=0.1=h6a83c73_3
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py311h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - graphviz=9.0.0=h51cb2cd_1
  - gts=0.7.6=h6b5321d_4
  - harfbuzz=10.2.0=he2f9f60_1
  - hf-xet=1.1.10=py310h63875d3_2
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py311haa95532_0
  - imageio=2.37.0=py311haa95532_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=7.0.1=pyh6dadd2b_0
  - ipython=9.6.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311haa95532_0
  - joblib=1.5.2=py311haa95532_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - khronos-opencl-icd-loader=2024.05.08=h8cc25b3_0
  - kiwisolver=1.4.8=py311h5da7b33_0
  - krb5=1.21.3=hdf4eb48_0
  - lazy_loader=0.4=py311haa95532_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libgd=2.3.3=ha43c60c_1
  - libglib=2.84.2=h405b238_0
  - libgomp=15.2.0=h1383e82_7
  - libiconv=1.16=h2bbff1b_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libkrb5=1.21.3=h885b0b7_4
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.6=h652a1e2_0
  - libsodium=1.0.20=hc70643c_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxgboost=3.0.5=cuda129_h8216274_1
  - libxml2=2.13.8=h866ff63_0
  - libzlib=1.3.1=h02ab6af_0
  - lightgbm=4.4.0=py311hda3d55a_1
  - lightning-utilities=0.11.9=py311haa95532_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib=3.10.6=py311haa95532_0
  - matplotlib-base=3.10.6=py311h43afe63_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - narwhals=2.9.0=pyhcf101f3_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=py311haa95532_0
  - numexpr=2.11.0=py311hdb065b2_0
  - numpy=2.0.1=py311hdab7c0b_1
  - numpy-base=2.0.1=py311hd01c5d8_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311ha5e6156_0
  - pango=1.50.14=h07c897b_2
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.42=h0ff8eda_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py311h096bfcc_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.3.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.1=py311h3485c13_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.0.5=cuda129_pyh3031c10_1
  - pycparser=2.23=py311haa95532_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.0=py311haa95532_0
  - pyqt=6.9.1=py311h12ec796_0
  - pyqt6-sip=13.10.2=py311h630b2a1_0
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.11.14=hd8ed1ab_2
  - python-graphviz=0.21=pyhbacfb6d_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytorch=2.5.1=py3.11_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=py311haa95532_0
  - pywin32=311=py311hefeebc8_1
  - pyyaml=6.0.2=py311h827c3e9_0
  - pyzmq=27.1.0=py311hb77b9c8_0
  - qtbase=6.9.2=h916ffc4_3
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - requests=2.32.5=py311haa95532_0
  - safetensors=0.6.2=py311h18438d6_1
  - scikit-image=0.25.2=py311h094160a_0
  - scikit-learn=1.7.1=py311h3fbe716_0
  - scipy=1.16.0=py311h242c13b_0
  - seaborn=0.13.2=py311haa95532_3
  - setuptools=80.9.0=py311haa95532_0
  - sip=6.12.0=py311h706e071_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.5.0=py311h746a85d_0
  - tifffile=2025.10.4=py311haa95532_0
  - timm=1.0.20=pyhcf101f3_0
  - tk=8.6.15=hf199647_0
  - torchmetrics=1.2.1=py311haa95532_0
  - tornado=6.5.2=py311h3485c13_1
  - tqdm=4.67.1=py311h746a85d_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - ttach=0.0.3=pyhd8ed1ab_0
  - typing-extensions=4.15.0=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py311haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - xgboost=3.0.5=cuda129_pyh5c66634_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - abnf==2.2.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - backoff==2.2.1
      - chardet==5.2.0
      - cint==1.0.0
      - click==8.3.0
      - cryptography==46.0.3
      - diskcache==5.6.3
      - ensemble-boxes==1.0.9
      - eval-type-backport==0.2.2
      - fickling==0.1.4
      - frozenlist==1.8.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gql==4.0.0
      - graphql-core==3.2.6
      - intervaltree==3.1.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kaitaistruct==0.11
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - llvmlite==0.45.1
      - multidict==6.7.0
      - numba==0.62.1
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - pdfminer-six==20250506
      - polars==1.34.0
      - polars-runtime-32==1.34.0
      - polyfile-weave==0.5.7
      - propcache==0.4.1
      - protobuf==6.33.0
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pyreadline3==3.5.4
      - referencing==0.37.0
      - requests-toolbelt==1.0.0
      - rpds-py==0.27.1
      - sentry-sdk==2.42.1
      - simsimd==6.5.3
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - stdlib-list==0.11.1
      - stringzilla==4.2.1
      - sympy==1.13.1
      - tenacity==9.1.2
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - typing-inspection==0.4.2
      - ultralytics==8.3.221
      - ultralytics-thop==2.0.17
      - wandb==0.22.2
      - weave==0.52.10
      - yarl==1.22.0
prefix: C:\Users\User\miniconda3\envs\final
