_wandb:
    value:
        cli_version: 0.22.2
        e:
            7cxdoo483rs40cr8rs7fmxs6f5dire85:
                codePath: image_classification.ipynb
                codePathLocal: image_classification.ipynb
                cpu_count: 12
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1023116570624"
                        used: "788359606272"
                email: galnoelpeterrindengan@gmail.com
                executable: c:\Users\User\miniconda3\envs\final\python.exe
                git:
                    commit: 5c3c232a45f739a84f2f9052eb0d0ae59ba88eb9
                    remote: https://github.com/galnoel/image-classification.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-117dbbd0-c0c9-124a-7a7a-d1c2b489372f
                host: DESKTOP-SN7AON1
                memory:
                    total: "16831713280"
                os: Windows-10-10.0.26200-SP0
                program: c:\data_\code\image-classification\image_classification.ipynb
                python: CPython 3.11.14
                root: c:\data_\code\image-classification
                startedAt: "2025-10-27T22:50:29.277753Z"
                writerId: 7cxdoo483rs40cr8rs7fmxs6f5dire85
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
                - 79
                - 80
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
                - 79
                - 80
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.14
            "5": 0.22.2
            "8":
                - 1
                - 3
            "12": 0.22.2
            "13": windows-amd64
data:
    value:
        test_dir: C:\data_\GEMASTIK\dataset_latihan\clean\test
        test_split_ratio: 0.2
        train_dir: C:\data_\GEMASTIK\dataset_latihan\clean\train
        val_dir: C:\data_\GEMASTIK\dataset_latihan\clean\val
data_params:
    value:
        batch_size: 32
        image_size: 224
        num_workers: 0
loss_function:
    value:
        name: CrossEntropyLoss
        params:
            alpha: 0.25
            gamma: 2
            reduction: mean
model_params:
    value:
        local_weights_dir: pretrained_models
        name: efficientnet_b0
        pretrained: true
outputs:
    value:
        base_dir: outputs
        cm_plot_path: '{run_folder}/confusion_matrix.png'
        cm_plot_path_finetuned: '{run_folder}/confusion_matrix_finetuned.png'
        log_file: '{run_folder}/run.log'
        model_path: '{run_folder}/best_model.pth'
        model_path_finetuned: '{run_folder}/best_model_finetuned.pth'
        report_path: '{run_folder}/results_report.pkl'
        report_path_finetuned: '{run_folder}/results_report_finetuned.pkl'
        submission_file: '{run_folder}/submission.csv'
        training_curves_plot_path: '{run_folder}/training_curves.png'
        training_curves_plot_path_finetuned: '{run_folder}/training_curves_finetuned.png'
train_params:
    value:
        epochs: 10
        finetune_epochs: 15
        finetune_learning_rate: 5e-05
        learning_rate: 0.001
        optimizer: AdamW
        scheduler:
            name: None
            params:
                T_max: 10
